language: node_js
node_js:
    - "0.12"
    - "0.11"
    - "0.10"
addons:
    code_climate:
        repo_token: 282b18ad2cab390c17d2cf2352ed03042333a41ec776a2144692da5be89dc038
after_script:
    - cat coverage/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js

